### ISSUE TITLE
MTM6201_01-midterm project struggling html responsive image 

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201-midterm#1]
@abhaysharma

I struggle to create responsive images on my website. The art direction responsive image is not working properly. Media is showing the smaller image on larger screens and the larger image on smaller screens. I only used Adobe XD export sizes.

cheer
Rebecca

**Comment by coop0162** [comment]
@abhaysharma
Is the nav bar at the fixed bottom of the page using HTML or CSS? Can I continue using the icons provided by the real estate website? Can we use the website's buttons, or do we need to make our own? Is it possible to change the font? I am having trouble retrieving the font from the Prototype real estate website.
Should start on the css?

**Comment by abhaysharma** [comment]
@coop0162  RE: responsive images
There are a few things to note:
1. You will need to remove one of the links from your source tag. lines 52-57 in index1.html
<picture>
            <source srcset="images/rooms/1008x567largeorangeroom.png " media="(min-width:300px)">
            <img class="orangrom" src="images/rooms/336x189smallorangeroom.png" alt="orange office with guitar">
</picture>
2. You will need to add width:100% to your img tag in your CSS

**Comment by abhaysharma** [comment]
@coop0162 
Is the nav bar at the fixed bottom of the page using HTML or CSS? 
Yes, you can use position: fixed on the nav. Also, you will need to add padding-bottom to the body tag equal to the height of your nav bar.

Can I continue using the icons provided by the real estate website? 
Yes, although I would recommend using an icon font library such as font-awesome.   

Can we use the website's buttons, or do we need to make our own? 
I am not certain about the exact buttons you are referring to. If they are the ones at the bottom of the page, you can create them using CSS.

Is it possible to change the font? I am having trouble retrieving the font from the Prototype real estate website.
Yes, you may use a differnet but matching font. Use Google Fonts service to add a web font.

Should start on the css?
Yes, you may start it once your HTML is complete.

Another thing to note is your index file must be named index.html and not index1.html
