### ISSUE TITLE
mtm6201   010 midterm- to much white space between the images

### ISSUE THREAD

**Issue by coop0162** [coop0162/mtm6201-midterm#4]
@abhaysharma
I am experiencing issues with aligning the font with the icons on Page 3.html .Specifically on lines 45 to 50 the line of text and icon are messy when attempted to CSS code.

.I have attempted to apply CSS to Index.html, but it has resulted in a significant gap between class="design-homes" and class="home-cont" on index.html.

**Comment by abhaysharma** [comment]
@coop0162 I am assuming this is regarding the images in the navigation. To fix your navigation yu will need the following:
- To the ul inside the nav, add display:flex;
- To the li inside the nav ul, add flex:1; display: flex; flex-direction: column
- To the img inside the nav ul li, add width: 40px
